### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by tharunc** [Akashsindhu/AIes_object_detection#5]
Hello,
    I would like to work on the readme.md file issue . Can you please assign it to me.

**Comment by himanshu007-creator** [comment]
sir, i would like to work on readme. Please assign me this issue

**Comment by Akashsindhu** [comment]
Re-open if you have anything.

**Comment by himanshu007-creator** [comment]
Please add DWOC label to this issue . I have sent a pull request https://github.com/Akashsindhu/AIes_object_detection/pull/12

**Comment by himanshu007-creator** [comment]
Sir please add a lever 2 tag to this issue, otherwise I will not get a score for leaderboard.
