### ISSUE TITLE
Contributing file 

### ISSUE THREAD

**Issue by akrish4** [Akashsindhu/AIes_object_detection#7]
Hi @Akashsindhu 
I would like to add contributing file @Akashsindhu 
Kindky assign me it

**Comment by akashsindhu96** [comment]
Closing this isssue. Open another if you want to.

**Comment by akrish4** [comment]
> Closing this isssue. Open another if you want to.

Kindly do re open this issue , Close once the pr is merged @Akashsindhu

**Comment by akrish4** [comment]
Kindly add the labels `DWOC` and `Level-3` or `Level-2` or `Level-1`  to issue  @Akashsindhu 
as this project is registered under dwoc

**Comment by akashsindhu96** [comment]
Could you explain what is DWOC?

**Comment by akrish4** [comment]
DWOC stands for DevScript Winter of code 
This project is registered in dwoc know so kindly do add the labels above mentioned to make it count towards open source contribution under dwoc

**Comment by akrish4** [comment]
#9 
Kindly do add the above labels to PR aswell  @Akashsindhu

**Comment by akrish4** [comment]
@Akashsindhu
